name: Deploy

on:
  push:
    branches:
      - main
      - staging
      - develop

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd admin-backend
          npm install

      - name: Run tests
        run: |
          cd admin-backend
          npm test

      - name: Deploy to server
        run: |
          # Add deployment commands here
          echo "Deploying backend to ${{ github.ref_name }} environment"

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd admin-frontend
          npm install

      - name: Build application
        run: |
          cd admin-frontend
          npm run build

      - name: Deploy to server
        run: |
          # Add deployment commands here
          echo "Deploying frontend to ${{ github.ref_name }} environment"