name: Build and Deploy to VPS

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        frontend: [customer-frontend, admin-frontend, superadmin-frontend]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: ${{ matrix.frontend }}/package-lock.json

      - name: Install dependencies
        working-directory: ./${{ matrix.frontend }}
        run: npm ci

      - name: Build frontend
        working-directory: ./${{ matrix.frontend }}
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.frontend }}-build
          path: |
            ${{ matrix.frontend }}/.next/
            ${{ matrix.frontend }}/public/
            ${{ matrix.frontend }}/package.json
            ${{ matrix.frontend }}/package-lock.json

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_PRIVATE_KEY }}
          script: |
            set -e

            WORK_DIR="/var/www/dev.davcreations.in/davcreations-rep"

            # Ensure PM2 is installed
            if ! command -v pm2 &> /dev/null; then
              echo "Installing PM2..."
              npm install -g pm2
            fi

            # Create work directory if it doesn't exist
            mkdir -p "$WORK_DIR"

            # Copy ecosystem config
            rsync -avz --delete ./ecosystem.config.js "$WORK_DIR/"

            # Deploy each frontend
            for frontend in customer-frontend admin-frontend superadmin-frontend; do
              echo "Deploying $frontend..."

              # Create frontend directory
              mkdir -p "$WORK_DIR/$frontend"

              # Sync built files
              rsync -avz --delete "./artifacts/$frontend-build/" "$WORK_DIR/$frontend/"

              # Install production dependencies only
              cd "$WORK_DIR/$frontend"
              npm ci --only=production
            done

            # Restart PM2 applications
            cd "$WORK_DIR"
            pm2 startOrRestart ecosystem.config.js
            pm2 save
